### ISSUE TITLE
如何使用修改小米平板5手写笔的默认功能

### ISSUE THREAD

**Issue by jack007-hub** [arnesacnussem/MiPenCustomizer#1]
修改小米平板5手写笔的默认功能，MiPenCustomizer-master.zip这个如何安装，辛苦大佬指教一下，感谢感谢！

**Comment by arnesacnussem** [comment]
@jack007-hub 这是个Xposed模块，目前我用的[LSPosed](https://github.com/LSPosed/LSPosed)框架，你下载的文件是源码，下载之后需要自行编译打包

因为我没想好这东西应该把按键改成什么功能，所以目前只写了我需要的几个功能，所以具体你想要把这两个按键改成什么功能，还需要你自己去修改这个程序的源码....

当然你也可以提个issue告诉我你需要什么功能，如果有空的话我会帮你写一下
